### ISSUE TITLE
Errors when installing package, then when running interpreter?

### ISSUE THREAD

**Issue by acfoltzer** [carl-eastlund/dracula#4]
Hi Carl,

I ran into a few errors when installing Dracula with `raco`; they appear to have come up during testing and building the documentation, however, so I'm not sure if they are critical. The full log is here: https://gist.github.com/acfoltzer/a07f78d238a40e2b0c9f

Also, when I try to load J-Bob in DrRacket, or really anything in ACL2 mode, it fails with this error:
![image](https://cloud.githubusercontent.com/assets/205266/12045052/f3e245d0-ae50-11e5-86a0-34e8d1f87ed5.png)

Any suggestions?

**Comment by carl-eastlund** [comment]
Thanks for the report.  It looks like a number of things changed in Racket 6.3 and Dracula needs to be updated.  I'm working on it now, in the meantime if you need to run Dracula I suggest using Racket 6.2 or 6.1.

**Comment by carl-eastlund** [comment]
Okay, I pushed changes to github to fix ACL2 and Modular ACL2 in Dracula.  I just set the package manager to update my packages, it should pick up the changes shortly.  I've tested the new version with Racket 6.1.1 and Racket 6.3, it appears to work in both.

**Comment by carl-eastlund** [comment]
And I was just able to install it from the package catalog, so it's all set now.

**Comment by acfoltzer** [comment]
Thanks!
